<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Volumen en lts</name>
   <tag></tag>
   <elementGuidId>f47d7a56-9d8b-4c00-a149-54c40e3d4a83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='formFile']/div/div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f621d870-852c-4575-9e86-b0e5504c494b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-4</value>
      <webElementGuid>221e02fa-400a-47fe-897f-52cbacb777c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Volumen en lts</value>
      <webElementGuid>ec52b885-4b6a-41f2-b442-55a3ddf6d89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formFile&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]</value>
      <webElementGuid>b65220ab-f1e7-4740-b183-b9c1f6dd6e22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formFile']/div/div[5]</value>
      <webElementGuid>31bc6e3a-2f35-430b-a4bf-1dadf26b3fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Altura en cm'])[1]/following::div[5]</value>
      <webElementGuid>38c0cc03-cf43-432e-9294-93910375521b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lado de Carga'])[1]/following::div[13]</value>
      <webElementGuid>66ab7d88-aec9-4df0-a34c-6a6e01ac77ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar imagen'])[1]/preceding::div[11]</value>
      <webElementGuid>d8fabdd1-a356-47ff-8bc2-047529a601d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[5]</value>
      <webElementGuid>aa825c9d-393c-4e5b-a31d-b778a8bc566c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Volumen en lts' or . = 'Volumen en lts')]</value>
      <webElementGuid>a2876ba9-0394-4473-9f9e-208e01df8d3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
