<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_lock_outline_form-control</name>
   <tag></tag>
   <elementGuidId>55fe065b-647e-42a3-9156-fc8efb68d843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b04f21ea-a8e6-495b-8083-73b6c5849837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>171ad66f-43a6-4681-a0a5-a8e5a66b8c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña...</value>
      <webElementGuid>e807492d-e0f0-4322-8722-91ecccdbe3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4d7daac9-4ae3-4127-b8ef-b479ad295633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page off-canvas-sidebar&quot;]/app-my-app[1]/app-layout[1]/app-login-cmp[1]/div[@class=&quot;wrapper wrapper-full-page&quot;]/div[@class=&quot;page-header login-page header-filter&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;col-lg-4 col-md-6 col-sm-6 ml-auto mr-auto&quot;]/form[@class=&quot;form ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;card card-login&quot;]/div[@class=&quot;card-body&quot;]/span[@class=&quot;bmd-form-group&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>5156fe23-6817-42c0-85ef-84a450b56bb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>4cd5d734-b410-467e-9792-febaee818ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/input</value>
      <webElementGuid>9c64e966-4c64-44e4-b975-eaaf6e0923e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Contraseña...' and @type = 'password']</value>
      <webElementGuid>04a86fcb-bb3a-4d3f-b7b4-97a1ea203186</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
