<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre_brand</name>
   <tag></tag>
   <elementGuidId>285055ee-9b00-42d2-ba5a-afc63a9dbc10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-input-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0cdb44e6-ac16-4b94-ba4a-2543d01b2753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>83b22eba-5f73-48a5-a57e-b96a7f5e01f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>brand</value>
      <webElementGuid>cfcf2816-f3ef-4a63-bbf7-ab6622ca73ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Marca</value>
      <webElementGuid>650c0985-a4d1-4e31-86a8-20cff98923ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dbdc9ab6-3a66-400d-bb83-9513eee80364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-1</value>
      <webElementGuid>5e769182-8e14-4a4c-8d32-3509ba01f283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8fcce3b3-b2c9-45de-9578-a4a0592754f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>07e31a63-168b-4ee7-8da7-e8384e061130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-1&quot;)</value>
      <webElementGuid>190d1ada-fb7c-4082-9dbb-da020e0303b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-1']</value>
      <webElementGuid>6b29e428-7156-4f9e-9ffb-1c7a1c5896dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formFile']/div/div[2]/mat-form-field/div/div/div/input</value>
      <webElementGuid>866e0080-651a-4d00-bf14-928062100857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-form-field/div/div/div/input</value>
      <webElementGuid>a77fbaf3-52ef-4892-929c-079e0fc5ffbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'brand' and @placeholder = 'Marca' and @type = 'text' and @id = 'mat-input-1']</value>
      <webElementGuid>391addb4-0956-45ab-b9ff-b6466ad33778</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
