<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email_form-control</name>
   <tag></tag>
   <elementGuidId>be91825b-e84a-4403-be90-3fcc7eacf16f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42e57864-6da3-4001-8e0f-3d906e7c0d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1a0f6dc4-122f-4b4d-b7f2-ccbc3f86f846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email...</value>
      <webElementGuid>c5e4b563-6111-4822-857d-8c96d467cf2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>59859d5e-c6d7-4cf0-8baf-f3889befd91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page off-canvas-sidebar&quot;]/app-my-app[1]/app-layout[1]/app-login-cmp[1]/div[@class=&quot;wrapper wrapper-full-page&quot;]/div[@class=&quot;page-header login-page header-filter&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;col-lg-4 col-md-6 col-sm-6 ml-auto mr-auto&quot;]/form[@class=&quot;form ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;card card-login&quot;]/div[@class=&quot;card-body&quot;]/span[@class=&quot;bmd-form-group&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>406802ad-5377-4a22-a94e-7de5b3cff32c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='email']</value>
      <webElementGuid>0617a0e6-5133-4242-897b-810faa249fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>67fe27ee-7e78-411a-9116-785e043282c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email...' and @type = 'email']</value>
      <webElementGuid>e21d5f0b-74d1-4b15-8e25-af278452d909</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
