<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Proveedores</name>
   <tag></tag>
   <elementGuidId>4ad33756-f933-44e5-8789-b08d43832d63</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Proveedores' or . = 'Proveedores')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#\32  > ul > li:nth-child(8) > a > span.sidebar-normal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-my-app/app-layout/div/div[1]/app-sidebar-cmp/div[2]/ul/li[2]/div/ul/li[8]/a/span[2]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d12703af-5223-4e69-93d7-b89d125d00a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar-normal</value>
      <webElementGuid>18007f4a-743d-448b-9eb9-b7e6ad7fe2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proveedores</value>
      <webElementGuid>5caef771-40c1-46d0-ad6f-cc8ba679e831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2&quot;)/ul[@class=&quot;nav&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]/span[@class=&quot;sidebar-normal&quot;]</value>
      <webElementGuid>887e75e7-fcc1-48f4-90ca-2ac1c310d4f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/ul/li[8]/a/span[2]</value>
      <webElementGuid>a6fd58f5-e9ee-4eda-81c4-c949a1e43ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='business_center'])[1]/following::span[1]</value>
      <webElementGuid>b8890e68-c161-496c-98e9-a63928771cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dispositivos'])[1]/following::span[2]</value>
      <webElementGuid>81f54ce8-c1e6-437c-990f-1ae63c45ad37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='local_shipping'])[1]/preceding::span[1]</value>
      <webElementGuid>cca0637e-beb1-4068-90e0-e7843984d5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehículos'])[1]/preceding::span[2]</value>
      <webElementGuid>a7c411eb-126d-4d8b-8aae-20c83eee9672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proveedores']/parent::*</value>
      <webElementGuid>9625bac2-bfd1-4ea8-9d29-e16db8b48380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a/span[2]</value>
      <webElementGuid>544cc2be-6b8a-4ab7-ab20-5a78527cf850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Proveedores' or . = 'Proveedores')]</value>
      <webElementGuid>82bbcfcd-e15e-4e06-8565-99b1359ea22f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
