<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_lock_outline_form-control (1)</name>
   <tag></tag>
   <elementGuidId>84b1b730-70fa-49c6-be81-f86054531f84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21f7676e-13c4-407e-b66a-cc3c59b31e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4322d2d8-824e-4383-845a-65657641d965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña...</value>
      <webElementGuid>3a687059-3687-4859-b2b6-9e1443cecb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>dc763957-37b8-4277-ac0f-6445dc65c2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page off-canvas-sidebar&quot;]/app-my-app[1]/app-layout[1]/app-login-cmp[1]/div[@class=&quot;wrapper wrapper-full-page&quot;]/div[@class=&quot;page-header login-page header-filter&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;col-lg-4 col-md-6 col-sm-6 ml-auto mr-auto&quot;]/form[@class=&quot;form ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;card card-login&quot;]/div[@class=&quot;card-body&quot;]/span[@class=&quot;bmd-form-group&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>4e89661b-f205-4e73-b757-570cb4ab82dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>9ac158df-0c5e-4d93-87c7-bb145663f1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/input</value>
      <webElementGuid>ff00b2a8-a45c-402b-ad32-daa4215e3f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Contraseña...' and @type = 'password']</value>
      <webElementGuid>8c72960a-3823-4390-9df7-7430c41d7589</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
