<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Altura de Calle_city (1)</name>
   <tag></tag>
   <elementGuidId>52863926-e5e4-44f3-b254-73f7570742cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-input-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c6d9398-76ad-4f00-a899-e9b05ed2a8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>e9d7cf07-55a3-4654-b854-e8a30d0971ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>535aaafe-e4f9-493d-9b8e-db94ccf5594c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>84bea4df-0b50-4403-906c-94270877a4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-3</value>
      <webElementGuid>b37a9003-b9a4-4927-a2c0-628014c063ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ciudad del Cliente</value>
      <webElementGuid>3bf1c1f7-5ed7-4f3a-8d06-f991fda74011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5736f3b2-2794-49ea-9a5c-bb4b221599b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>04921e2e-fba9-46b3-add6-f258b8c4e5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-3&quot;)</value>
      <webElementGuid>6768589c-7672-429c-be61-6d5da79d271f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-3']</value>
      <webElementGuid>e724d33d-abbe-4d2d-bb73-214eff45f4a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/mat-form-field/div/div/div/input</value>
      <webElementGuid>7c37d81a-3f11-498c-9fec-ddf9ea2e1f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'city' and @id = 'mat-input-3' and @placeholder = 'Ciudad del Cliente']</value>
      <webElementGuid>5c404ca7-bb07-41be-8422-327c15b9efd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
