<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sitio N4721</name>
   <tag></tag>
   <elementGuidId>0cafc081-ab5e-4212-8df6-10b8300a2b7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-26']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-26 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>47b4d3f1-7e3e-4785-83ae-39efb82fd7b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>5a910708-b068-4452-898f-913fa26006d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sitio N°4721 </value>
      <webElementGuid>12cccad7-563d-42fc-b7a5-d65fb4d66357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-26&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>97a7facd-882f-4af8-91fc-69db7fdd4b1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-26']/span</value>
      <webElementGuid>313167a2-c7be-402f-8ac1-a509b14cb6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sitio N°1009'])[1]/following::span[1]</value>
      <webElementGuid>8676d13c-9502-4685-950b-201a07288ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sitio N°2493'])[1]/following::span[2]</value>
      <webElementGuid>c5f015c0-3517-4053-a9cb-ccb71655a2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sitio N°3062'])[1]/preceding::span[1]</value>
      <webElementGuid>3d5dd836-cac4-4433-9b5c-c39fa2374b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sitio N°4049'])[1]/preceding::span[2]</value>
      <webElementGuid>ab417372-3235-4ff5-8da6-2d42977f308b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sitio N°4721']/parent::*</value>
      <webElementGuid>5c408200-5d88-4f29-ac02-b32dba743597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[4]/span</value>
      <webElementGuid>54fb2673-b1d8-461f-8364-8870e5f6ccce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Sitio N°4721 ' or . = ' Sitio N°4721 ')]</value>
      <webElementGuid>7301fd8b-4bba-4e43-adfd-57b3a0b7bf9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
