<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_lock_outline_form-control (1)</name>
   <tag></tag>
   <elementGuidId>e1bb07f5-2029-4980-8e65-10bc28772b24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cdc7d319-157c-404e-a187-d10449855619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>19ba53c4-7620-4dcb-b552-e82c2b978751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña...</value>
      <webElementGuid>c492c348-3805-43f7-894e-c01450d9641a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e88881a9-73d0-4323-88b3-e3f5887000a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page off-canvas-sidebar&quot;]/app-my-app[1]/app-layout[1]/app-login-cmp[1]/div[@class=&quot;wrapper wrapper-full-page&quot;]/div[@class=&quot;page-header login-page header-filter&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;col-lg-4 col-md-6 col-sm-6 ml-auto mr-auto&quot;]/form[@class=&quot;form ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;card card-login&quot;]/div[@class=&quot;card-body&quot;]/span[@class=&quot;bmd-form-group&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>369ed48f-447b-49b5-93d3-3fb1d8667939</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>ef6f883b-aded-4e86-acbf-76c07eebb872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/input</value>
      <webElementGuid>71c3727a-df8e-47bc-becc-eca9661d3888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Contraseña...' and @type = 'password']</value>
      <webElementGuid>575888fa-17a2-4f9c-b6c3-6cdb93b8c374</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
