<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_check</name>
   <tag></tag>
   <elementGuidId>f75069db-19d7-4bc0-aa8e-0d99ea6c2a57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-just-icon.btn-round.mat-mini-fab.mat-accent.cdk-focused.cdk-mouse-focused > span.mat-button-wrapper > mat-icon.mat-icon.material-icons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']/app-route-info-modal/div[2]/button[2]/span/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>d32397a1-a7d2-4a34-b37a-9d1ee0960457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon material-icons</value>
      <webElementGuid>514c3673-18c6-4cb0-ab33-84835fa204ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3542bb93-e99a-4e99-8b5d-0ba95dff67f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>03a4927c-cd06-4497-b39c-8423001594b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>check</value>
      <webElementGuid>09d3f12e-d6a0-4285-a2ac-f56072526765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/app-route-info-modal[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-dialog-actions&quot;]/button[@class=&quot;btn btn-primary btn-just-icon btn-round mat-mini-fab mat-accent cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/mat-icon[@class=&quot;mat-icon material-icons&quot;]</value>
      <webElementGuid>ecf2e59e-134f-4e4d-aca1-289a117cbaae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/app-route-info-modal/div[2]/button[2]/span/mat-icon</value>
      <webElementGuid>49321454-c7a7-4dd9-a51f-920fcb937213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos de mapas ©2022 Google'])[4]/following::mat-icon[2]</value>
      <webElementGuid>8b260014-cd02-42b8-b6d5-c24036dfe1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notificar un problema de Maps'])[2]/following::mat-icon[2]</value>
      <webElementGuid>67d52fa9-4d6c-451e-a2bd-55d337d4115a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/mat-icon</value>
      <webElementGuid>54216751-b0cd-42ca-b91d-48c53ed7e44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'check' or . = 'check')]</value>
      <webElementGuid>b736128b-f15f-45d0-8460-a1e56d2c3f17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
