<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Depsito_mat-select-arrow</name>
   <tag></tag>
   <elementGuidId>63fac3f0-4ff9-4b75-9820-2b55cc9e05ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='mat-select-0']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-select-arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1e254986-a762-4950-b86f-ca929ee95b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-arrow</value>
      <webElementGuid>53f5d9b7-2410-4168-bc68-8f74e357bb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-0&quot;)/div[@class=&quot;mat-select-trigger&quot;]/div[@class=&quot;mat-select-arrow-wrapper&quot;]/div[@class=&quot;mat-select-arrow&quot;]</value>
      <webElementGuid>3acf7e20-ad5b-4b95-83c2-d159d67fe46a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-0']/div/div[2]/div</value>
      <webElementGuid>ac66b9e2-6ffe-4834-bb93-adb615e6efad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-select/div/div[2]/div</value>
      <webElementGuid>41437f03-930d-4b47-8691-75269e11a5bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
