<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Clientes</name>
   <tag></tag>
   <elementGuidId>ff3247da-e400-4344-9622-9140ec8b0dc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1']/ul/li/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1 > ul.nav > li.nav-item > a.nav-link > span.sidebar-normal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5ab27ab3-517c-4656-8ae0-375e1aa99363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar-normal</value>
      <webElementGuid>f939bd1a-1b01-492a-87d1-0a06e90ba636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clientes</value>
      <webElementGuid>e0847357-d33a-4560-a821-10960cc16de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)/ul[@class=&quot;nav&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]/span[@class=&quot;sidebar-normal&quot;]</value>
      <webElementGuid>40893cd1-94f2-4940-986c-c8a54a8292ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/ul/li/a/span[2]</value>
      <webElementGuid>94c12184-df89-40c7-a6c8-2d74f969fb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info'])[1]/following::span[1]</value>
      <webElementGuid>3ff24af7-376b-4573-816e-10b25f244268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='assessment'])[1]/following::span[2]</value>
      <webElementGuid>ee1c3e2a-f979-45fe-a93c-fa2e186974a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='card_travel'])[1]/preceding::span[1]</value>
      <webElementGuid>cbe469ff-2fe2-4217-af9f-3e110b2912e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Productos'])[1]/preceding::span[2]</value>
      <webElementGuid>0fe8dfc1-3229-45f7-9f4c-f24427b0d141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clientes']/parent::*</value>
      <webElementGuid>d3edf9e0-f772-4330-ad84-ca01a807042d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/ul/li/a/span[2]</value>
      <webElementGuid>99c401d6-6016-4249-ad67-94ba40b7f4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Clientes' or . = 'Clientes')]</value>
      <webElementGuid>7cce3cee-8d44-4c78-b6c8-6d062e7fbf30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
